### ISSUE TITLE
[4JH] Nmap CRUD

### ISSUE THREAD

**Issue by lambdina** [vrn-sh/erp#19]
## Describe the issue 
Scan nmap CRUD. Nmap is a basic tool for pentesters that allows to scan remote machine executions, with a lot of options.

## Resource request
N/A

## Definition of done 

- [x] Should have a model
    - [x] Should have the exact command
    - [x] Should have the output in raw
    - [x] Should contains the date
    - [ ] Should contains a tag indicating the relevance of the output
    - [ ] Should have the exact version of nmap used
- [x] CREATE: create an nmap model with POST / CREATE method.
- [x] PUT: edit nmap model
- [x] DELETE: delete nmap model
- [x] READ: get nmap model that has already been added
- [x] Django Unit tests
- [x] POSTMAN api

## Testing plan
unit tests

## JEH
4

**Comment by djnnvx** [comment]
Following the [nmap output format](https://nmap.org/book/output.html), we need to store specific elements of data in our database. You can find here an example output, but it's important to note that output will not always be the same because it depends on what kind of options the user enables: 

```bash
Nmap 5.35DC18 scan initiated Sun Jul 18 15:33:26 2010 as: ./nmap -T4 -A -oN - scanme.nmap.org
Nmap scan report for scanme.nmap.org (64.13.134.52)
Host is up (0.045s latency).
Not shown: 993 filtered ports
PORT      STATE  SERVICE VERSION
22/tcp    open   ssh     OpenSSH 4.3 (protocol 2.0)
| ssh-hostkey: 1024 60:ac:4d:51:b1:cd:85:09:12:16:92:76:1d:5d:27:6e (DSA)
|_2048 2c:22:75:60:4b:c3:3b:18:a2:97:2c:96:7e:28:dc:dd (RSA)
25/tcp    closed smtp
53/tcp    open   domain
70/tcp    closed gopher
80/tcp    open   http    Apache httpd 2.2.3 ((CentOS))
| http-methods: Potentially risky methods: TRACE
|_See https://nmap.org/nsedoc/scripts/http-methods.html
|_html-title: Go ahead and ScanMe!
113/tcp   closed auth
31337/tcp closed Elite
Device type: general purpose
Running: Linux 2.6.X
OS details: Linux 2.6.13 - 2.6.31, Linux 2.6.18
Network Distance: 13 hops

TRACEROUTE (using port 80/tcp)
HOP RTT       ADDRESS
[Cut first 10 hops for brevity]
11  45.16 ms  layer42.car2.sanjose2.level3.net (4.59.4.78)
12  43.97 ms  xe6-2.core1.svk.layer42.net (69.36.239.221)
13  45.15 ms  scanme.nmap.org (64.13.134.52)

OS and Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
# Nmap done at Sun Jul 18 15:33:48 2010 -- 1 IP address (1 host up) scanned in 22.47 seconds
```

> this is the most verbose option, so this is the one i will use for this explaination

We need to have an array of `Port` fields, with inside the following properties: `ServiceName` (can be empty), `PortNumber`, `Version` (can be empty), `Metadata` (can be empty), and finally a field specifying whether the port is open for `UDP` or `TCP` 

In the `Nmap` model there also needs to be:
- an `IPAddress` field in the model, 
- a timestamp for the time it was submitted, 
- a `TextField` for the domain name, 
- a dynamic property counting the number of open ports

By default, nmap parser typically support `xml`, but we want the default `nmap` result that you can get from the command-line, because this is the one that is most likely to be used.

It seems [this library](https://pypi.org/project/python-libnmap/) has not been maintained in a long time, but it could still work. We should also check whether any big CVEs can work with it before adding it to the project, of course. If we can't add it, you can take inspiration from this library for the parser.
